image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
    - build
    - test
    - deploy
    
variables:
    APP_NAME: medplatformapi

   
build:
    stage: build
    before_script:
    - echo xd
    - "cd MedPlatform"
    - "dotnet restore" 
    script:
        - "dotnet build"
test:
    stage: test
    script:
        - "dotnet restore"
        - "dotnet build"
deploy:
    image: docker:latest
    services:
        - docker:dind
    stage: deploy
    script:
        - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
        - docker pull $CI_REGISTRY_IMAGE:latest
        - docker tag $CI_REGISTRY_IMAGE:latest $HEROKU_REGISTRY_IMAGE:latest
        - docker login --username=_ --password=$HEROKU_API_KEY $HEROKU_REGISTRY
        - docker push $HEROKU_REGISTRY_IMAGE:latest
        - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli container:release web --app $APP_NAME
    
        